# Zettelkasten ID
name: zkID
parent: default

global_vars: 
  - name: zk_time
    type: date
    params:
      format: "%d%m%Y%H%M"

matches:
  - trigger: ":id"
    replace: "{{zk_time}}"
  - trigger: ":link"
    replace: "[[{{zk_time}}]]"
    
# This is an extra feature for URLs in markdown
matches:
  - trigger: ":url"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"
        
# Why not?
matches:
  - trigger: ":flip"
    replace: "`(╯°□°）╯︵ ┻━┻`"
