# Zettelkasten ID
name: zkID
parent: default

global_vars: 
  - name: zk_time
    type: date
    params:
      format: "%m%d%Y%H%M"

matches:
  - trigger: ":id"
    replace: "{{zk_time}}"
  - trigger: ":link"
    replace: "[Link Text][{{zk_time}}]"
